### ISSUE TITLE
" key not working

### ISSUE THREAD

**Issue by saavor** [rjanicek/vice.js#9]
## the " key does not function correctly
This does not allow print to function.

**Comment by Sgeo** [comment]
This vice.js build is using something approximating the positional keyboard. The C64 had its " key on shift-2, so press that.

There might be browser-specific variations in some other keys, because Emscripten's SDL1 implementation isn't very portable.

I'm working on a build that defaults to symbolic keymapping (" on PC = " in emulator) and can be switched to positional, and won't have oddities in different browsers. Mostly just fixing the Emscripten SDL1 implementation.

**Comment by saavor** [comment]
ok
